Add more error log

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -114,7 +114,14 @@ runs:
           -X POST \
           --data "$DATA" \
           ${{ inputs.webhook }} > $TMP
-        [ -s $TMP ] && echo "::error title=Non-204 response::Discord did not respond with expected status.\nResponse: $(cat $TMP)"
+        if [ -s $TMP ]
+        then
+          echo "::error title=Faild to send message::Discord did not respond with expected status."
+          echo "Non-204 status" >> $GITHUB_STEP_SUMMARY
+          echo "Temporary file: $TMP" >> $GITHUB_STEP_SUMMARY
+          cat $TMP >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
     - name: 'Send webhook message on Windows'
       if: runner.os == 'Windows'
       shell: pwsh
